openapi: 3.0.0
servers:
  - description: Customer API
    url: http://localhost:8080
info:
  description: "CRUD Operations for customer"
  version: "1.0.0"
  title: "Customer API"
  contact:
    email: "choreo-help@wso2.com"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
tags:
  - name: "customer"
    description: "customer api"
  - name: "demo"
    description: "This api is created for demo purposes"
paths:
  /greeting:
    get:
      summary: "Greet a customer"
      operationId: "getCustomerById"
      description: |
        Greet a customer
      parameters:
        - name: name
          in: query
          description: "Customer name"
          required: true
          schema:
            type: string
      responses:
        "200":
          description: "Greeting for customer"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Customer"

        "404":
          description: "Unable to find the Customer"

components:
  schemas:
    Customer:
      type: object
      required:
        - id
        - content
      properties:
        accountId:
          type: string
          example: "1"
        content:
          type: string
          example: "Hello, John"
